# https://github.com/microsoft/pyright
[tool.pyright]
include = ["src"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/.*",
    "src/vendor",
]
venv = "uniblocker"
typeCheckingMode = "off"
useLibraryCodeForTypes = false

# https://github.com/charliermarsh/ruff
[tool.ruff]
fix = true
line-length = 88
target-version = "py38"
[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "I",   # isort
]
ignore = ["E402", "E501", "E722", "E731"]
# https://github.com/timothycrosley/isort/
[tool.ruff.lint.isort]
combine-as-imports = true
