#!/usr/bin/env python

import os

from src.utils.lit_cli import LitCLI


def main():
    os.chdir(os.path.dirname(__file__))

    LitCLI(
        parser_kwargs={
            "default_config_files": ["configs/presets/default.yaml"],
        },
        save_config_overwrite=True,
    )


if __name__ == "__main__":
    main()
