seed_everything: 123
trainer:
  max_epochs: 5
  callbacks+:
    - class_path: src.callbacks.Evaluator
model:
  class_path: src.models.SentenceTransformer
  init_args:
    model_name_or_path: ./models/Qwen/Qwen3-Embedding-8B
    max_length: 256
    hidden_dropout_prob: 0.15
    pooler_type: last_token
    temperature: 0.01
    learning_rate: 2.0e-05
    adam_epsilon: 1.0e-08
    warmup_steps: 0
    weight_decay: 0.0
    scheduler_type: linear
